services:
  - type: web
    name: ubuntium-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_KEY_PATH
        sync: false
